### ISSUE TITLE
Unexpected rounding when multiplying

### ISSUE THREAD

**Issue by eborden** [PaulJohnson/Haskell-Decimal#10]
This seems like unexpected behavior:

``` Haskell
import Data.Decimal (Decimal, roundTo, (*.))

test :: IO ()
test = do
  let x = roundTo 2 (25 :: Decimal)
      y = 6.5e-2 :: Double
      z = 25 :: Double
  print $ x *. y                       -- 1.62
  print $ roundTo 3 x *. y             -- 1.625
  print . roundTo 2 $ roundTo 3 x *. y -- 1.63
  print $ y * z                        -- 1.625

```

I would expect multiplication by a `RealFrac` to do the unbounded multiplication and then round to my prescribed precision. Instead this seems to be truncating the decimal place.

If I am incorrect in this assumption then the documentation should be updated.

Additionally I'm seeing the same behavior here:

``` Haskell
print . realFracToDecimal 2 $ y * z  -- 1.62
```

Thanks.

**Comment by eborden** [comment]
After a bit more testing, I've discovered that `round` is utilizing bankers rounding. Closing.

**Comment by PaulJohnson** [comment]
Actually "roundTo" does not use bankers rounding. It is supposed to round halves away from zero. However I have to say that, given the intended application in finance, bankers would be the Right Thing. I'll look into it.

**Comment by eborden** [comment]
This is actually not an issue with `roundTo`, but `*.`

**Comment by PaulJohnson** [comment]
roundTo will now use Bankers Rounding.

**Comment by eborden** [comment]
Thanks for following up on this!
