### ISSUE TITLE
Data.Number.Fixed is not decimal arithmetic

### ISSUE THREAD

**Issue by stiell** [PaulJohnson/Haskell-Decimal#12]
`README.txt` refers to `Data.Number.Fixed` from the `numbers` package as an alternative implementation of decimal arithmetic. However, that implementation performs arithmetic on `Rational` values and rounds them using `approxRational`, resulting in rounding errors that would not appear in decimal arithmetic. E.g.:
```
λ> 0.3333330000 / 10 :: Fixed Prec10
0.0333332999
```

`README.txt` should be corrected, possibly removing the reference altogether as it is not relevant to decimal arithmetic.

**Comment by PaulJohnson** [comment]
Agreed. The reference is removed in 0.5.1.
