### ISSUE TITLE
Broken Num implementation for non-Integer bases

### ISSUE THREAD

**Issue by charles-cooper** [PaulJohnson/Haskell-Decimal#13]
I'm not sure if this is expected behavior but this just seems wrong:
```
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Prelude> import Data.Decimal as D
Prelude D> import Data.Int as I
Prelude D I> (1::DecimalRaw Int64) * 1
0
```
I would guess that the `maxBound` of `256` in the (`realFracToDecimal`) is too much for `Int64`.

**Comment by PaulJohnson** [comment]
The documentation warns against arithmetic in "DecimalRaw i" for i /= Integer.  This kind of thing is the reason why.
