### ISSUE TITLE
10.00 :: Decimal, confusing

### ISSUE THREAD

**Issue by reuleaux** [PaulJohnson/Haskell-Decimal#14]
Not sure if this is an issue, but I find this confusing at least:

I get division as expected (and as explained in the introductory section of the docs)
when using decimals like so (this is the number ten divided by three):

>>> 

```haskell
> (Decimal 2 1000) `divide` 3
[(2,3.33),(1,3.34)]
>
```
Likewise I can read decimal numbers:
```haskell
> (read "10.00" :: Decimal) `divide` 3
[(2,3.33),(1,3.34)]
>
```
And I would expect the result to be the same when just using `10.00::Decimal`,
but that's not the case:
```haskell
> (10.00 :: Decimal) `divide` 3
[(2,3),(1,4)]
> 
```
As apparently these are different Decimal numbers:
```haskell
> read "10.00" :: Decimal
10.00
> 10.00 :: Decimal
10
>
```
I wonder: how do people cope with this in practice? should I really write
`(read "10.00" :: Decimal)` all over?

**Comment by PaulJohnson** [comment]
Yes, I agree its confusing. But apart from adding a note to the documentation I don't know what to do about it. The literal `10.00` gets translated into `fromRational (10 % 1)` by the Haskell compiler, so the trailing zeros in the source code are lost before Decimal can see them.

There are a number of workarounds. You've given two, and another would be `realFracToDecimal 2 10`, which would do the Right Thing. You could also write something like `toDollars = realFracToDecimal 2` if you are going to have a lot of dollar denominated literals.

**Comment by reuleaux** [comment]
OK, thanks for your feedback, I will try the other workarounds
as well.
