### ISSUE TITLE
toInteger for Decimal?

### ISSUE THREAD

**Issue by jD91mZM2** [PaulJohnson/Haskell-Decimal#19]
Hey, I'm trying to convert a Decimal to an integer.

```
No instance for (Integral Decimal) arising from a use of ‘toInteger’
```

Is this currently possible?

**Comment by PaulJohnson** [comment]
That's because Decimal is not an integer type. It is an instance of RealFrac, which gives you truncate, round, ceiling and floor, the same as Float and Double.

**Comment by jD91mZM2** [comment]
Aha, thanks!
