### ISSUE TITLE
Replace "mantissa" with "significand"

### ISSUE THREAD

**Issue by bradyt** [PaulJohnson/Haskell-Decimal#21]
The use of word "mantissa" here is appearing in some auto generated api terms, in hledger-web. The api doesn't yet have sufficient documentation, so one would be faced with determining what "mantissa" means. The usage here is like that of "significand". I think "significand" would lead to less ambiguity. A user of any auto generated user-facing tool would potentially have to find this library by following the source, to see what you have at the README, to clarify.

See https://github.com/simonmichael/hledger/issues/1178.

**Comment by PaulJohnson** [comment]
This would be a breaking change, so I'm not doing it.

See my response on the hledger bug for more on this.
