### ISSUE TITLE
Int mantissa problem

### ISSUE THREAD

**Issue by wojtnar** [PaulJohnson/Haskell-Decimal#3]
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
Prelude> :m +Data.Decimal 
Prelude Data.Decimal> type DecOnInt = DecimalRaw Int
Prelude Data.Decimal> 1.0 :: DecOnInt 
0
Prelude Data.Decimal> 1/2 :: DecOnInt 
0

-- Whereas this works
Prelude Data.Decimal> let a = Decimal {decimalPlaces = 2, decimalMantissa = (1::Int)}
Prelude Data.Decimal> let b = Decimal {decimalPlaces = 2, decimalMantissa = (2::Int)}
Prelude Data.Decimal> a
0.01
Prelude Data.Decimal> b
0.02
Prelude Data.Decimal> a+b
0.03

**Comment by gittywithexcitement** [comment]
@PaulJohnson, since this is fixed, shouldn't you close the issue?
