### ISSUE TITLE
Do we need the pesky datatype context on DecimalRaw?

### ISSUE THREAD

**Issue by ericpashman** [PaulJohnson/Haskell-Decimal#6]
Hi,  Paul. Thanks for putting together a useful library.

I've noticed that it's not possible to derive an instance of `Generic` (from `GHC.Generics`) for `DecimalRaw` due to the `Integral` constraint in its definition:

```
> :set -XStandaloneDeriving
> deriving instance Generic (DecimalRaw i)

<interactive>:13:1:
    Can't make a derived instance of ‘Generic (DecimalRaw i)’:
      DecimalRaw must not have a datatype context
    In the stand-alone deriving instance for ‘Generic (DecimalRaw i)’
```

This is quite a convenient thing to be able to do, as you can use generics to derive instances for parsing and serializing JSON representations with Aeson, for example. At the same time, [putting class constraints on datatype definitions is pretty much useless](https://ghc.haskell.org/trac/haskell-prime/wiki/NoDatatypeContexts) and is broadly considered an anti-pattern.

Looking at the code, it seems to me that the `Integral` constraint can be removed from the definition of `DecimalRaw` with zero effect on the library's operation. Is there something I'm missing? If not, are you open to getting rid of it?

**Comment by saurabhnanda** [comment]
It this in anyways related the following error that I'm running into:

```
   35  15 error           error:
     • No instance for (FromJSON (Data.Decimal.DecimalRaw Integer))
         arising from a use of ‘genericParseJSON’
     • In the expression: genericParseJSON $ aesonPrefix snakeCase
       In an equation for ‘parseJSON’:
           parseJSON = genericParseJSON $ aesonPrefix snakeCase
       In the instance declaration for ‘FromJSON Booking’ (intero)
```

What's the fastest way to fix this?

**Comment by PaulJohnson** [comment]
@saurabhnanda, no I don't believe so. The spurious type context was removed in 0.4.2. I don't use generic derivation myself, but it looks from the error message like you need to define a FromJSON instance for DecimalRaw manually.

**Comment by saurabhnanda** [comment]
Is it a good idea to have Data.Decimal itself define the JSON instances?

**Comment by PaulJohnson** [comment]
I thought about it, and decided not to. I can see it would make life easier for people who want to put Decimal values in JSON, but it would also mean that everyone using Decimal would have to drag aeson into their build even if they don't use it.

**Comment by ericpashman** [comment]
I think that's the right decision.

Saurabh, FYI, it's easy to get automatically generated Aeson instances for the Decimal datatype by declaring orphan instances of the Generic and Aeson typeclasses for it in your own code, using the -XStandaloneDeriving extension alongside -XDeriveGeneric. See the GHC User's Guide for details: https://downloads.haskell.org/~ghc/8.0.2/docs/html/users_guide/glasgow_exts.html#stand-alone-deriving-declarations

**Comment by simonmichael** [comment]
@ericpashman can you remember the exact code required ? For me, using GHC 8.6 this compiles:
```haskell
{-# LANGUAGE DeriveAnyClass      #-}
{-# LANGUAGE DeriveGeneric       #-}
...
deriving instance Generic Decimal
instance FromJSON Decimal
```
I haven't figured out if it's correct yet.

**Comment by simonmichael** [comment]
Also, for others who may come this way: I was getting an error message like "invalid content: expected record (:*:), encountered Number". https://github.com/bos/aeson/issues/474 mentioned that deriving instances using Aesons's deriveFromJSON gives better messages, and indeed after replacing the above with:
```haskell
{-# LANGUAGE TemplateHaskell       #-}
...
$(deriveFromJSON defaultOptions ''DecimalRaw)
```
I see the more helpful "invalid content: When parsing the constructor Decimal of type Data.Decimal.DecimalRaw expected Object but got Number."

(`$(deriveFromJSON defaultOptions ''Decimal)` didn't compile: "normalizeDecFor: DataD or NewtypeD required").

I'm not sure what kind of json object the auto-derived instance is looking for, no doubt I'll find out soon.

Clearly I'm confused, but maybe the above will help someone else. It would be great if this just worked. https://stackoverflow.com/questions/40331851/haskell-data-decimal-as-aeson-type#comment67918863_40331851 recommends to "solve" it by switching to [scientific](https://hackage.haskell.org/package/scientific-0.3.4.9) instead. (Something I'd rather not do.. assuming Decimal is still a reasonable choice ?)

**Comment by simonmichael** [comment]
Correct json format: `{"decimalMantissa":123, "decimalPlaces":2}`.

**Comment by ericpashman** [comment]
@simonmichael, I think the code in your first comment should work if it compiles—though “work” doesn’t mean you can parse a JSON number into a `Decimal`, as you’ve discovered.

Error messages with these extensions are always rather cryptic, but I’d prefer them to Template Haskell. Typically you’ll want to start by getting a generic `ToJSON` instance working, then use that to figure out what the `FromJSON` instance expects to parse: for a correct instance, `encode` and `decode` should give you an isomorphism between your type and `Bytestring` (up to the `Maybe` wrapper that `decode` returns).

I don’t have time to test it right now, but I think it will also work without `DeriveAnyClass`, just using `DeriveGeneric` and `StandAloneDeriving`. It should also work to use the [`genericParseJSON`](
http://hackage.haskell.org/package/aeson/docs/Data-Aeson.html#v:genericParseJSON) function to implement the class explicitly, something like this:

```haskell
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE StandAloneDeriving #-}

import GHC.Generics
import Data.Aeson

deriving instance Generic Decimal

instance FromJSON Decimal where
  parseJSON = genericParseJSON defaultOptions
```

And of course you can avoid `StandAloneDeriving` entirely if you’re willing to wrap `Decimal` in your own `newtype`.

It looks like you’ve got it figured out, but if you don’t get it working fully, let me know and I’ll provide some real code tomorrow.

**Comment by simonmichael** [comment]
Thanks @ericpashman. JSON in Haskell is a serious business!

**Comment by ericpashman** [comment]
Ha, well, it’s fairly straightforward if you’re willing to write your instances yourself, rather than trying to get the compiler to do it for you. If you haven’t done that before, you should give it a go. You can of course also write parsers that do things like take a JSON number directly into a `Decimal` when you write the instances yourself—it’s just that the compiler can only figure out how to write an instance if it’s entirely determined by the structure of the type.
