### ISSUE TITLE
Add a way to convert to Double

### ISSUE THREAD

**Issue by k-bx** [PaulJohnson/Haskell-Decimal#8]
Currently, I couldn't figure out anything better than:

```haskell
fromRational (toRational (1/3::Decimal)) :: Double
```

Also, it is never convenient to search through type-classes, so I'd suggest adding some "toDouble" function.

Thanks!

**Comment by PaulJohnson** [comment]
Actually the Prelude function "realToFrac" does what you want.
    realToFrac :: (Real a, Fractional b) => a -> b
    realToFrac = fromRational . toRational

    realToFrac (1/3::Decimal) :: Double

**Comment by k-bx** [comment]
I see now. Thanks!
